rest:
  address:
    ip: "0.0.0.0"
    port: 8080
  timeout:
    write: 15
    read: 15
    idle: 60
  endpoints:
    - name: "GetPerson"
      method: "GET"
      path: "/person/{id}"
      handler: "GetPerson"
    - name: "AddPerson"
      method: "POST"
      path: "/person"
      handler: "AddPerson"
grpc:
  port: 50051